/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import static Admin.Main.f;
import Resources.ConnectionProvider;

import java.awt.Dimension;
import java.awt.HeadlessException;
import javax.swing.*;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author kkk
 */
public class AddProducts extends javax.swing.JPanel {

    private final String Integerpattern = "^[1-9]\\d*$";
    private final String decimalpattern = "^[0-9]*\\.?[0-9]+$";
    private int CheckName = 0;

    /**
     * Creates new form AddProducts
     */
    public AddProducts() {
        Toolkit tk = Toolkit.getDefaultToolkit(); //Initializing the Toolkit class.
        Dimension screenSize = tk.getScreenSize(); //Get the Screen resolution of our device.
        this.setSize(screenSize.width, screenSize.height); //Set the width and height of the JFrame.

        initComponents();
        types();
        Companies();
    }

    private void types() {
        Connection con;
        Statement stm;
        ResultSet rs;
        try {
            con = ConnectionProvider.getcon();
            stm = con.createStatement();
            rs = stm.executeQuery("select * from types");

            while (rs.next()) {
                typecombotxt.addItem(rs.getString("type_name"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void Companies() {
        Connection con;
        Statement stm;
        ResultSet rs;
        try {
            con = ConnectionProvider.getcon();
            stm = con.createStatement();
            rs = stm.executeQuery("select * from companies");

            while (rs.next()) {
                distributorcombotxt.addItem(rs.getString("company_name"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        APL = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        APR = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        formulatxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        typecombotxt = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        distributorcombotxt = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        packstxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        loosetxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        quantityinpacktxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        priceofpacktxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        wpriceofpacktxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        discountratetxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        minimumquantitytxt = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jButton16 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        Iconlabel1 = new javax.swing.JLabel();

        APL.setBackground(new java.awt.Color(0, 0, 102));
        APL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        APL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jButton8.setText(" REPORTS");
        jButton8.setAlignmentY(0.0F);
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton8.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        APL.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 260, 60));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suppliers.png"))); // NOI18N
        jButton9.setText(" DISTRIBUTORS ");
        jButton9.setAlignmentY(0.0F);
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton9.setIconTextGap(0);
        jButton9.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        APL.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 260, 60));

        jButton6.setBackground(new java.awt.Color(204, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ITEMS.png"))); // NOI18N
        jButton6.setText("  PRODUCTS");
        jButton6.setAlignmentY(0.0F);
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        APL.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 280, 60));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        jButton11.setText("    DASHBOARD");
        jButton11.setAlignmentY(0.0F);
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton11.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        APL.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 260, 60));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage users.png"))); // NOI18N
        jButton12.setText("     USERS   ");
        jButton12.setAlignmentY(0.0F);
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton12.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        APL.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 260, 60));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pos.png"))); // NOI18N
        jButton7.setText("       POS     ");
        jButton7.setAlignmentX(0.5F);
        jButton7.setAlignmentY(0.0F);
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        APL.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 260, 60));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 178, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN\n");
        APL.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton3.setText("  LOGOUT ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        APL.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 723, 140, 40));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        jButton10.setText("  HISTORY");
        jButton10.setAlignmentY(0.0F);
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton10.setIconTextGap(5);
        jButton10.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        APL.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 260, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile(2).png"))); // NOI18N
        APL.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 180, 190));

        APR.setBackground(new java.awt.Color(204, 255, 255));
        APR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        APR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        APR.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 30, 30));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setForeground(new java.awt.Color(204, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorder(null);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        APR.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 30, 30));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        APR.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1020, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("ADD PRODUCT");
        APR.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 350, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Name");
        APR.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, 20));

        nametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        nametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nametxtKeyReleased(evt);
            }
        });
        APR.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Formula");
        APR.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, -1));

        formulatxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        formulatxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        formulatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulatxtActionPerformed(evt);
            }
        });
        APR.add(formulatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 300, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Type");
        APR.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        typecombotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        typecombotxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        APR.add(typecombotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 300, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Distributor");
        APR.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        distributorcombotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        distributorcombotxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        APR.add(distributorcombotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 300, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Packs/Boxes");
        APR.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 20));

        packstxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        packstxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        packstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packstxtActionPerformed(evt);
            }
        });
        APR.add(packstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 300, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("loose");
        APR.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, 20));

        loosetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loosetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loosetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loosetxtActionPerformed(evt);
            }
        });
        loosetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loosetxtKeyReleased(evt);
            }
        });
        APR.add(loosetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 300, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Quantity In Pack");
        APR.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        quantityinpacktxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityinpacktxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        quantityinpacktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityinpacktxtActionPerformed(evt);
            }
        });
        quantityinpacktxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityinpacktxtKeyReleased(evt);
            }
        });
        APR.add(quantityinpacktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 300, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Price Of Pack");
        APR.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        priceofpacktxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceofpacktxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        priceofpacktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofpacktxtActionPerformed(evt);
            }
        });
        APR.add(priceofpacktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 300, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Wholesale Pack Price");
        APR.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, 20));

        wpriceofpacktxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wpriceofpacktxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wpriceofpacktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpriceofpacktxtActionPerformed(evt);
            }
        });
        APR.add(wpriceofpacktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 300, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Discount Rate");
        APR.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        discountratetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        discountratetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        discountratetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountratetxtActionPerformed(evt);
            }
        });
        APR.add(discountratetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 300, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Minimum Quantity");
        APR.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        minimumquantitytxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minimumquantitytxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        minimumquantitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimumquantitytxtActionPerformed(evt);
            }
        });
        APR.add(minimumquantitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 300, -1));

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        APR.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 40, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton4.setText(" Add");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setIconTextGap(10);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        APR.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 110, 40));

        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        APR.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1090, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        APR.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1090, 10));

        jButton16.setBackground(new java.awt.Color(255, 255, 204));
        jButton16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit Products.png"))); // NOI18N
        jButton16.setText(" Edit Products ");
        jButton16.setToolTipText("");
        jButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        APR.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 250, 100));

        jButton13.setBackground(new java.awt.Color(153, 153, 153));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add company.png"))); // NOI18N
        jButton13.setText(" Add Company");
        jButton13.setToolTipText("");
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        APR.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, 250, 100));

        jButton15.setBackground(new java.awt.Color(102, 204, 255));
        jButton15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add category.png"))); // NOI18N
        jButton15.setText("<html>&ensp;Add Product<br>&emsp;&ensp;Type</html>");
        jButton15.setToolTipText("");
        jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton15.setIconTextGap(5);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        APR.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 250, 100));

        jButton14.setBackground(new java.awt.Color(204, 255, 204));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add product.png"))); // NOI18N
        jButton14.setText(" Add Product ");
        jButton14.setToolTipText("");
        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        APR.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 260, 120));
        APR.add(Iconlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(APL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(APR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(APL, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(APR, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new Reports());
        f.revalidate();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new ManageDistributors());
        f.revalidate();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new AdminDashboard());
        f.revalidate();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new ManageUsers());
        f.revalidate();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new PosPanel());
        f.revalidate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new LoginPanel());
        f.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new History());
        f.revalidate();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Do you really want to close this application?", "Pharmacy Management System",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        f.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void nametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametxtKeyReleased
        // TODO add your handling code here:
        String name = nametxt.getText();

        if (!name.equals("")) {
            Iconlabel1.setVisible(true);
            Iconlabel1.setIcon(new ImageIcon("src\\images\\yes.png"));
            Iconlabel1.setText("");
            CheckName = 0;

            Connection myConn = null;
            Statement myStmt = null;
            ResultSet myRs = null;

            try {
                // 1. Get a connection to database
                myConn = ConnectionProvider.getcon();

                // 2. Create a statement
                myStmt = myConn.createStatement();

                // 3. Execute SQL query
                myRs = myStmt.executeQuery("select * from products where name = '" + name + "'");

                while (myRs.next()) {
                    CheckName = 1;
                    Iconlabel1.setIcon(new ImageIcon("src\\images\\no.png"));
                    Iconlabel1.setText("");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            Iconlabel1.setVisible(false);
        }
    }//GEN-LAST:event_nametxtKeyReleased

    private void formulatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formulatxtActionPerformed

    private void packstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packstxtActionPerformed

    private void loosetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loosetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loosetxtActionPerformed

    private void loosetxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loosetxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loosetxtKeyReleased

    private void quantityinpacktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityinpacktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityinpacktxtActionPerformed

    private void quantityinpacktxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityinpacktxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityinpacktxtKeyReleased

    private void priceofpacktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofpacktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofpacktxtActionPerformed

    private void wpriceofpacktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpriceofpacktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wpriceofpacktxtActionPerformed

    private void discountratetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountratetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountratetxtActionPerformed

    private void minimumquantitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimumquantitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimumquantitytxtActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        nametxt.setText("");
        formulatxt.setText("");
        typecombotxt.setSelectedItem("Cap\\Tab");
        typecombotxt.setSelectedItem("gsk");
        packstxt.setText("");
        loosetxt.setText("");
        quantityinpacktxt.setText("");
        priceofpacktxt.setText("");
        wpriceofpacktxt.setText("");
        minimumquantitytxt.setText("");
        discountratetxt.setText("");
        minimumquantitytxt.setText("");
        Iconlabel1.setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String name = nametxt.getText();
        String formula = formulatxt.getText();
        String type = (String) typecombotxt.getSelectedItem();
        String company = (String) distributorcombotxt.getSelectedItem();
        String packs = packstxt.getText();
        String loose = loosetxt.getText();
        String quantity_in_pack = quantityinpacktxt.getText();
        String price_of_pack = priceofpacktxt.getText();
        String wprice_of_pack = wpriceofpacktxt.getText();
        String discount_rate = discountratetxt.getText();
        String minimum_quantity = minimumquantitytxt.getText();

        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "Name cannot be empty!");
        } else if (formula.equals("")) {
            JOptionPane.showMessageDialog(null, "Formula cannot be empty!");
        } else if (packs.equals("")) {
            JOptionPane.showMessageDialog(null, "'packs' field cannot be empty!");
        } else if (!packs.matches(Integerpattern) && !packs.equals("0")) {
            JOptionPane.showMessageDialog(null, "Invalid pattern!\n'Packs/Boxes' field should contain integers only.");
        } else if (loose.equals("")) {
            JOptionPane.showMessageDialog(null, "'loose' field can not be empty!");
        } else if (!loose.matches(Integerpattern) && !loose.equals("0")) {
            JOptionPane.showMessageDialog(null, "Invalid pattern!\n'Loose' field should contain integers only.");
        } else if (quantity_in_pack.equals("")) {
            JOptionPane.showMessageDialog(null, "'Quantity In Pack' field cannot be empty!");
        } else if (!quantity_in_pack.matches(Integerpattern)) {
            JOptionPane.showMessageDialog(null, "'Quantity In Pack' field should contain 'Integers' only!");
        } else if (quantity_in_pack.equals("0")) {
            JOptionPane.showMessageDialog(null, "'Quantity In Pack' can not be zero!");
        } else if (price_of_pack.equals("")) {
            JOptionPane.showMessageDialog(null, "'Price Of Pack' cannot be empty!");
        } else if (price_of_pack.equals("0")) {
            JOptionPane.showMessageDialog(null, "'Price Of Pack' can not be zero!");
        } else if (!price_of_pack.matches(decimalpattern) && !price_of_pack.matches(Integerpattern)) {
            JOptionPane.showMessageDialog(null, "Invlaid pattern!\n'Price Of Pack' field should contain integers or decimal values.");
        } else if (wprice_of_pack.equals("")) {
            JOptionPane.showMessageDialog(null, "'Wholesale Price Of Pack' cannot be empty!");
        } else if (!wprice_of_pack.matches(decimalpattern) && !wprice_of_pack.matches(Integerpattern)) {
            JOptionPane.showMessageDialog(null, "Invalid pattern!\n'Wholesale Price Of Pack' field should contain integers or decimal values.");
        } else if (discount_rate.equals("")) {
            JOptionPane.showMessageDialog(null, "'Discount Rate' cannot be empty!");
        } else if (!discount_rate.matches(decimalpattern) && !discount_rate.matches(Integerpattern)) {
            JOptionPane.showMessageDialog(null, "Invalid 'Discount Rate' pattern!\n'Discount Rate' field should contain integers or decimal values.");
        } else if (minimum_quantity.equals("")) {
            JOptionPane.showMessageDialog(null, "'Minimum Quantity' cannot be empty!");
        } else if (!minimum_quantity.matches(Integerpattern)) {
            JOptionPane.showMessageDialog(null, "Invalid pattern!\n'Minimum Quantity' field should contain integers only.");
        } else if (CheckName == 1) {
            JOptionPane.showMessageDialog(null, "Username already exists!\nPlease enter another Username.");
        } else {

            Connection con;
            PreparedStatement stm;

            try {
                con = ConnectionProvider.getcon();
                stm = con.prepareStatement("insert into products (name,formula,type,company,packs,loose,quantity_in_packs,price_of_pack,wprice_of_pack,price_of_loose,discount_rate,minimum_quantity) values(?,?,?,?,?,?,?,?,?,?,?,?)");

                stm.setString(1, name);
                stm.setString(2, formula);
                stm.setString(3, type);
                stm.setString(4, company);
                stm.setString(5, packs);
                stm.setString(6, loose);
                stm.setString(7, quantity_in_pack);
                stm.setString(8, price_of_pack);
                stm.setString(9, wprice_of_pack);

                Float price_of_loose = Float.valueOf(price_of_pack) / Float.valueOf(quantity_in_pack);
                stm.setString(10, price_of_loose.toString());

                stm.setString(11, discount_rate);
                stm.setString(12, minimum_quantity);

                stm.executeUpdate();

                JOptionPane.showMessageDialog(null, "Product added successfully!");
                jButton17ActionPerformed(evt);

            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new EditProducts());
        f.revalidate();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new AddCompany());
        f.revalidate();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new AddType());
        f.revalidate();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel APL;
    private javax.swing.JPanel APR;
    private javax.swing.JLabel Iconlabel1;
    private javax.swing.JTextField discountratetxt;
    private javax.swing.JComboBox<String> distributorcombotxt;
    private javax.swing.JTextField formulatxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField loosetxt;
    private javax.swing.JTextField minimumquantitytxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField packstxt;
    private javax.swing.JTextField priceofpacktxt;
    private javax.swing.JTextField quantityinpacktxt;
    private javax.swing.JComboBox<String> typecombotxt;
    private javax.swing.JTextField wpriceofpacktxt;
    // End of variables declaration//GEN-END:variables
}
