/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import static Admin.Main.f;
import Resources.name;
import Resources.ConnectionProvider;
import EditRemoveRaven.TableActionCellEditor;
import EditRemoveRaven.TableActionCellRender;
import EditRemoveRaven.TableActionEvent;

import java.awt.Dimension;
import java.awt.HeadlessException;
import javax.swing.*;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kkk
 */
public class ManageUsers extends javax.swing.JPanel {

    private String EmailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    private String MobileNumberPattern = "^[0-9]*$";
    private String SalaryPattern = "^\\d+$";
    public int CheckUserName = 0;

    /**
     * Creates new form ManageUsers
     */
    public ManageUsers() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit(); //Initializing the Toolkit class.
        Dimension screenSize = tk.getScreenSize(); //Get the Screen resolution of our device.
        this.setSize(screenSize.width, screenSize.height); //Set the width and height of the JFrame.

        initComponents();
        //Iconlabel.setVisible(false);

        TableActionEvent event;
        event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {

                int index = jTable1.getSelectedRow();

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                String first_name = model.getValueAt(index, 1).toString();
                String last_name = model.getValueAt(index, 2).toString();
                String type = model.getValueAt(index, 4).toString();
                String mobile_number = model.getValueAt(index, 5).toString();
                String email = (String) model.getValueAt(index, 6);
                String salary = (String) model.getValueAt(index, 7);

                editfirstnametxt.setText(first_name);
                editlastnametxt.setText(last_name);
                editusertypecombo.setSelectedItem(type);
                editmobilenumbertxt.setText(mobile_number);
                editemailtxt.setText(email);
                editsalarytxt.setText(salary);

            }

            @Override
            public void onDelete(int row) {
                if (jTable1.isEditing()) {
                    jTable1.getCellEditor().stopCellEditing();

                }
                int index = jTable1.getSelectedRow();

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                String id = model.getValueAt(index, 0).toString();
                String usernameTable = model.getValueAt(index, 3).toString();

                if (usernameTable.equals(name.getThisUser())) {
                    JOptionPane.showMessageDialog(null, "You cannot delete your own account");
                } else {

                    int result = JOptionPane.showConfirmDialog(null, "Do you really want to delete the user with username: " + usernameTable, "Pharmacy Management System",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                    if (result == JOptionPane.YES_OPTION) {

                        Connection con;
                        PreparedStatement stm;

                        try {
                            con = ConnectionProvider.getcon();
                            stm = con.prepareStatement("DELETE FROM `pharmacy`.`users` WHERE (`id` = '" + id + "') and (`user_name` = '" + usernameTable + "');");
                            stm.execute();
                            model.removeRow(row);
                            JOptionPane.showMessageDialog(null, "User deleted successfully!");
                        } catch (HeadlessException | SQLException e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        }
                    }
                }
            }
        };

        jTable1.getColumnModel().getColumn(8).setCellRenderer(new TableActionCellRender());
        jTable1.getColumnModel().getColumn(8).setCellEditor(new TableActionCellEditor(event));
        jTable1ComponentShown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserR = new javax.swing.JPanel();
        editusertypecombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editlastnametxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        salarytxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lastnametxt = new javax.swing.JTextField();
        usernametxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mobilenumbertxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editIconlabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        firstnametxt = new javax.swing.JTextField();
        editemailtxt = new javax.swing.JTextField();
        editfirstnametxt = new javax.swing.JTextField();
        editsalarytxt = new javax.swing.JTextField();
        editmobilenumbertxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        usertypecombo = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        Iconlabel2 = new javax.swing.JLabel();
        Iconlabel1 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        Iconlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userL = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        UserR.setBackground(new java.awt.Color(204, 255, 255));
        UserR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        UserR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editusertypecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASHIER", "ADMIN" }));
        editusertypecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editusertypecomboActionPerformed(evt);
            }
        });
        UserR.add(editusertypecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("USER TYPE");
        UserR.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 70, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("FIRST NAME");
        UserR.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 80, -1));
        UserR.add(editlastnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("LAST NAME");
        UserR.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        salarytxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salarytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarytxtActionPerformed(evt);
            }
        });
        UserR.add(salarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 221, 340, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("USER NAME");
        UserR.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        lastnametxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lastnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnametxtActionPerformed(evt);
            }
        });
        UserR.add(lastnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 221, 340, 30));

        usernametxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        usernametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernametxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernametxtKeyTyped(evt);
            }
        });
        UserR.add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 81, 340, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("MOBILE NUMBER");
        UserR.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        mobilenumbertxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mobilenumbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenumbertxtActionPerformed(evt);
            }
        });
        mobilenumbertxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobilenumbertxtKeyReleased(evt);
            }
        });
        UserR.add(mobilenumbertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 281, 340, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SALARY");
        UserR.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("PASSWORD");
        UserR.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        passwordtxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        passwordtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordtxtKeyReleased(evt);
            }
        });
        UserR.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 151, 340, 30));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton4.setText("  Add");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        UserR.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 100, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("EMAIL");
        UserR.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, 20));

        emailtxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        UserR.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 281, 340, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CURRENT USERS");
        UserR.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 350, 50));
        UserR.add(editIconlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 590, 30, 20));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UserR.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1090, -1));

        firstnametxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        firstnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnametxtActionPerformed(evt);
            }
        });
        UserR.add(firstnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 151, 340, 30));
        UserR.add(editemailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 640, 250, -1));
        UserR.add(editfirstnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 250, -1));

        editsalarytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editsalarytxtActionPerformed(evt);
            }
        });
        UserR.add(editsalarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 690, 250, -1));

        editmobilenumbertxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editmobilenumbertxtKeyReleased(evt);
            }
        });
        UserR.add(editmobilenumbertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, 250, -1));

        jLabel14.setText("Last_Name");
        UserR.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, -1, -1));

        jLabel15.setText("Type");
        UserR.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, -1));

        jLabel16.setText("Mobile_Number");
        UserR.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 570, -1, -1));

        jLabel17.setText("Email");
        UserR.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, -1, -1));

        jLabel18.setText("Salary");
        UserR.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 670, -1, -1));

        jLabel19.setText("First_Name");
        UserR.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, -1, -1));

        usertypecombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usertypecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASHIER", "ADMIN" }));
        UserR.add(usertypecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 81, 340, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("ADD USER");
        UserR.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 350, 50));

        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UserR.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1030, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton5.setText(" Save Changes");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        UserR.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 720, 140, 30));
        UserR.add(Iconlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 30, 30));
        UserR.add(Iconlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, 30, 30));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        UserR.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 30, 30));

        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UserR.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1090, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setForeground(new java.awt.Color(204, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorder(null);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        UserR.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 30, 30));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        UserR.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 30, 30));

        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UserR.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1090, -1));

        Iconlabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IconlabelKeyReleased(evt);
            }
        });
        UserR.add(Iconlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 130, 30, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First_Name", "Last_Name", "User_Name", "Type", "Mobile_Number", "Email", "Salary", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setName(""); // NOI18N
        jTable1.setRowHeight(40);
        jTable1.setSelectionBackground(new java.awt.Color(0, 195, 210));
        jTable1.setShowGrid(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        UserR.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 780, 340));

        userL.setBackground(new java.awt.Color(0, 0, 102));
        userL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ITEMS.png"))); // NOI18N
        jButton6.setText(" PRODUCTS");
        jButton6.setAlignmentY(0.0F);
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        userL.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 260, 60));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pos.png"))); // NOI18N
        jButton7.setText("       POS     ");
        jButton7.setAlignmentX(0.5F);
        jButton7.setAlignmentY(0.0F);
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        userL.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 260, 60));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jButton8.setText(" REPORTS");
        jButton8.setAlignmentY(0.0F);
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton8.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        userL.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 260, 60));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suppliers.png"))); // NOI18N
        jButton9.setText(" DISTRIBUTORS ");
        jButton9.setAlignmentY(0.0F);
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton9.setIconTextGap(0);
        jButton9.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        userL.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 260, 60));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        jButton10.setText("  HISTORY");
        jButton10.setAlignmentY(0.0F);
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton10.setIconTextGap(5);
        jButton10.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        userL.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 260, 60));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        jButton11.setText("    DASHBOARD");
        jButton11.setAlignmentY(0.0F);
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton11.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        userL.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 260, 60));

        jButton12.setBackground(new java.awt.Color(204, 255, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage users.png"))); // NOI18N
        jButton12.setText("   USERS   ");
        jButton12.setAlignmentY(0.0F);
        jButton12.setBorder(null);
        jButton12.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        userL.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 280, 60));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton3.setText("  LOGOUT ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        userL.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 723, 140, 40));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 178, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN\n");
        userL.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile(2).png"))); // NOI18N
        userL.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 180, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(userL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UserR, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userL, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserR, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editusertypecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editusertypecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editusertypecomboActionPerformed

    private void salarytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarytxtActionPerformed

    private void lastnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnametxtActionPerformed

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void usernametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernametxtKeyReleased
        // TODO add your handling code here:
        String username = usernametxt.getText();

        if (!username.equals("")) {
            Iconlabel1.setVisible(true);
            Iconlabel1.setIcon(new ImageIcon("src\\images\\yes.png"));
            Iconlabel1.setText("");
            CheckUserName = 0;

            Connection myConn = null;
            Statement myStmt = null;
            ResultSet myRs = null;

            try {
                // 1. Get a connection to database
                myConn = ConnectionProvider.getcon();

                // 2. Create a statement
                myStmt = myConn.createStatement();

                // 3. Execute SQL query
                myRs = myStmt.executeQuery("select * from users where user_name = '" + username + "'");

                while (myRs.next()) {
                    CheckUserName = 1;
                    Iconlabel1.setIcon(new ImageIcon("src\\images\\no.png"));
                    Iconlabel1.setText("");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            Iconlabel1.setVisible(false);
        }
    }//GEN-LAST:event_usernametxtKeyReleased

    private void usernametxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernametxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtKeyTyped

    private void mobilenumbertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenumbertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenumbertxtActionPerformed

    private void mobilenumbertxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobilenumbertxtKeyReleased
        // TODO add your handling code here:
        String mobile_number = mobilenumbertxt.getText();

        if (!mobile_number.equals("")) {
            Iconlabel2.setVisible(true);
            Iconlabel2.setIcon(new ImageIcon("src\\images\\no.png"));
            Iconlabel2.setText("");

            if (mobile_number.length() != 11) {
                Iconlabel2.setIcon(new ImageIcon("src\\images\\no.png"));
                Iconlabel2.setText("");
            } else {
                Iconlabel2.setIcon(new ImageIcon("src\\images\\yes.png"));
            }
        } else {
            Iconlabel2.setVisible(false);
        }
    }//GEN-LAST:event_mobilenumbertxtKeyReleased

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void passwordtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordtxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String user_type = (String) usertypecombo.getSelectedItem();
        String first_name = firstnametxt.getText();
        String last_name = lastnametxt.getText();
        String mobile_number = mobilenumbertxt.getText();
        String user_name = usernametxt.getText();
        String password = passwordtxt.getText();
        String email = emailtxt.getText();
        String salary = salarytxt.getText();

        if (first_name.equals("")) {
            JOptionPane.showMessageDialog(null, "First name cannot be empty!");
        } else if (last_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Last name cannot be empty!");
        } else if (mobile_number.equals("")) {
            JOptionPane.showMessageDialog(null, "Mobile number cannot be empty!");
        } else if (!mobile_number.matches(MobileNumberPattern) || mobile_number.length() != 11) {
            JOptionPane.showMessageDialog(null, "Invalid mobile number!");
        } else if (user_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Username cannot be empty!");
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "Password cannot be empty!");
        } else if (!email.matches(EmailPattern) && !email.equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid email pattern!");
        } else if (!salary.matches(SalaryPattern) && !(salary.equals(""))) {
            JOptionPane.showMessageDialog(null, "Invalid salary pattern!\nSalary should contain 'Integers' only.");
        } else if (CheckUserName == 1) {
            JOptionPane.showMessageDialog(null, "Username already exists!\nPlease enter another Username.");
        } else {

            Connection con;
            PreparedStatement stm;

            try {
                con = ConnectionProvider.getcon();
                stm = con.prepareStatement("insert into users (type,first_name,last_name,user_name,password,mobile_number,email,salary) values(?,?,?,?,?,?,?,?)");

                stm.setString(1, user_type);
                stm.setString(2, first_name);
                stm.setString(3, last_name);
                stm.setString(4, user_name);
                stm.setString(5, password);
                stm.setString(6, mobile_number);
                stm.setString(7, email);
                stm.setString(8, salary);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(null, "User added successfully!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void jTable1ComponentShown() {                                       
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        try {
            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            Connection con = ConnectionProvider.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * From users");

            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("id"), rs.getString("first_name"), rs.getString("last_name"), rs.getString("user_name"),
                    rs.getString("type"), rs.getString("mobile_number"), rs.getString("email"), rs.getString("salary")});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void firstnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnametxtActionPerformed

    private void editsalarytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editsalarytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editsalarytxtActionPerformed

    private void editmobilenumbertxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editmobilenumbertxtKeyReleased
        // TODO add your handling code here:
        String mobile_number = editmobilenumbertxt.getText();

        if (!mobile_number.equals("")) {
            editIconlabel.setVisible(true);
            editIconlabel.setIcon(new ImageIcon("src\\images\\no.png"));
            editIconlabel.setText("");

            if (mobile_number.length() != 11) {
                editIconlabel.setIcon(new ImageIcon("src\\images\\no.png"));
                editIconlabel.setText("");
            } else {
                editIconlabel.setIcon(new ImageIcon("src\\images\\yes.png"));
            }
        } else {
            editIconlabel.setVisible(false);
        }
    }//GEN-LAST:event_editmobilenumbertxtKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        int index = jTable1.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        String user_name = model.getValueAt(index, 3).toString();

        String user_type = (String) editusertypecombo.getSelectedItem();
        String first_name = editfirstnametxt.getText();
        String last_name = editlastnametxt.getText();
        String mobile_number = editmobilenumbertxt.getText();
        String email = editemailtxt.getText();
        String salary = editsalarytxt.getText();

        if (first_name.equals("")) {
            JOptionPane.showMessageDialog(null, "First name cannot be empty!");
        } else if (last_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Last name cannot be empty!");
        } else if (mobile_number.equals("")) {
            JOptionPane.showMessageDialog(null, "Mobile number cannot be empty!");
        } else if (!mobile_number.matches(MobileNumberPattern) || mobile_number.length() != 11) {
            JOptionPane.showMessageDialog(null, "Invalid mobile number!");
        } else if (!email.matches(EmailPattern) && !email.equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid email pattern!");
        } else if (!salary.matches(SalaryPattern) && !(salary.equals(""))) {
            JOptionPane.showMessageDialog(null, "Invalid salary pattern!\nSalary should contain 'Integers' only.");
        } else if (CheckUserName == 1) {
            JOptionPane.showMessageDialog(null, "Username already exists!\nPlease enter another Username");
        } else {

            Connection con;
            PreparedStatement stm;

            try {
                con = ConnectionProvider.getcon();
                stm = con.prepareStatement("UPDATE `pharmacy`.`users` SET `type` = ? , `first_name` = ? , `last_name` = ? , `mobile_number` = ? , `email` = ? , `salary` = ? WHERE (`id` = ?) and (`user_name` = ?);");

                stm.setString(1, user_type);
                stm.setString(2, first_name);
                stm.setString(3, last_name);
                stm.setString(4, mobile_number);
                stm.setString(5, email);
                stm.setString(6, salary);
                stm.setString(7, id);
                stm.setString(8, user_name);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(null, "Changes Saved successfully!");

                //refreshing the table
                jTable1ComponentShown();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        usertypecombo.setSelectedItem("CASHIER");
        firstnametxt.setText("");
        lastnametxt.setText("");
        mobilenumbertxt.setText("");
        usernametxt.setText("");
        passwordtxt.setText("");
        emailtxt.setText("");
        salarytxt.setText("");
        Iconlabel1.setVisible(false);
        Iconlabel2.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Main.f.setExtendedState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Do you really want to close this application?", "Pharmacy Management System",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IconlabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IconlabelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_IconlabelKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new EditProducts());
        f.revalidate();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new PosPanel());
        f.revalidate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new Reports());
        f.revalidate();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new ManageDistributors());
        f.revalidate();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        f.getContentPane().removeAll();
        f.getContentPane().add(new History());
        f.revalidate();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new AdminDashboard());
        f.revalidate();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new LoginPanel());
        f.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        try {
            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            Connection con = ConnectionProvider.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * From users");

            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("id"), rs.getString("first_name"), rs.getString("last_name"), rs.getString("user_name"),
                    rs.getString("type"), rs.getString("mobile_number"), rs.getString("email"), rs.getString("salary")});
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTable1ComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Iconlabel;
    private javax.swing.JLabel Iconlabel1;
    private javax.swing.JLabel Iconlabel2;
    private javax.swing.JPanel UserR;
    private javax.swing.JLabel editIconlabel;
    private javax.swing.JTextField editemailtxt;
    private javax.swing.JTextField editfirstnametxt;
    private javax.swing.JTextField editlastnametxt;
    private javax.swing.JTextField editmobilenumbertxt;
    private javax.swing.JTextField editsalarytxt;
    private javax.swing.JComboBox<String> editusertypecombo;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JTextField mobilenumbertxt;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JTextField salarytxt;
    private javax.swing.JPanel userL;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JComboBox<String> usertypecombo;
    // End of variables declaration//GEN-END:variables
}
