/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import static Admin.Main.f;

import EditRemoveRaven.TableActionCellEditor;
import EditRemoveRaven.TableActionCellRender;
import EditRemoveRaven.TableActionEvent;
import Resources.ConnectionProvider;
import java.awt.Dimension;
import java.awt.HeadlessException;
import javax.swing.*;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kkk
 */
public class ManageDistributors extends javax.swing.JPanel {

    /**
     * Creates new form ManageDistributors
     */
    private final String MobileNumberPattern = "^[0-9]*$";
    private final String integerPattern = "^[1-9]\\d*$";
    private final String decimalpattern = "[0-9]*['. ']?[0-9]*";
    int CheckName = 0;

    public ManageDistributors() {
        Toolkit tk = Toolkit.getDefaultToolkit(); //Initializing the Toolkit class.
        Dimension screenSize = tk.getScreenSize(); //Get the Screen resolution of our device.
        this.setSize(screenSize.width, screenSize.height); //Set the width and height of the JFrame.

        initComponents();

        TableActionEvent event;
        event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {

                int index = jTable1.getSelectedRow();

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                String company_name = (String) model.getValueAt(index, 1);
                String supplier = (String) model.getValueAt(index, 2);
                String contact = (String) model.getValueAt(index, 3);
                String balance = (String) model.getValueAt(index, 4);

                companynametxt.setText(company_name);
                suppliertxt.setText(supplier);
                contacttxt.setText(contact);
                balancetxt.setText(balance);

            }

            @Override
            public void onDelete(int row) {
                if (jTable1.isEditing()) {
                    jTable1.getCellEditor().stopCellEditing();
                }
                
                int index = jTable1.getSelectedRow();

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                String company_name = (String) model.getValueAt(index, 0);
                
                int result = JOptionPane.showConfirmDialog(null, "Do you really want to delete  '" + company_name + "'", "Pharmacy Management System",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                if (result == JOptionPane.YES_OPTION) {

                    Connection con;
                    PreparedStatement stm;

                    try {
                        con = ConnectionProvider.getcon();
                        stm = con.prepareStatement("DELETE FROM `pharmacy`.`distributors` WHERE (`company_name` = '" + company_name + "');");
                        stm.execute();

                        model.removeRow(row);

                        JOptionPane.showMessageDialog(null, "Distributor removed successfully!");

                    } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(null, "Error"+e.getMessage());
                    }
                }
            }
        };

        jTable1.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender());
        jTable1.getColumnModel().getColumn(5).setCellEditor(new TableActionCellEditor(event));
        jTable1ComponentShown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageDistributorsL = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        ManageDistributorsR = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        companynametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        suppliertxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        contacttxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        balancetxt = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Iconlabel2 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        ManageDistributorsL.setBackground(new java.awt.Color(0, 0, 102));
        ManageDistributorsL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ManageDistributorsL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage users.png"))); // NOI18N
        jButton12.setText("     USERS   ");
        jButton12.setAlignmentY(0.0F);
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton12.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        ManageDistributorsL.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 260, 60));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        jButton11.setText("    DASHBOARD");
        jButton11.setAlignmentY(0.0F);
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        ManageDistributorsL.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 260, 60));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton3.setText("  LOGOUT ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        ManageDistributorsL.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 723, 140, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile(2).png"))); // NOI18N
        ManageDistributorsL.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 180, 190));

        jButton9.setBackground(new java.awt.Color(204, 255, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suppliers.png"))); // NOI18N
        jButton9.setText(" DISTRIBUTORS  ");
        jButton9.setAlignmentY(0.0F);
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton9.setIconTextGap(10);
        jButton9.setInheritsPopupMenu(true);
        jButton9.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        ManageDistributorsL.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 280, 60));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jButton8.setText(" REPORTS");
        jButton8.setAlignmentY(0.0F);
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton8.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        ManageDistributorsL.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 260, 60));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        jButton13.setText("  HISTORY");
        jButton13.setAlignmentY(0.0F);
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton13.setIconTextGap(5);
        jButton13.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        ManageDistributorsL.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 260, 60));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ITEMS.png"))); // NOI18N
        jButton6.setText(" PRODUCTS");
        jButton6.setAlignmentY(0.0F);
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        ManageDistributorsL.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 260, 60));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 178, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN\n");
        ManageDistributorsL.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pos.png"))); // NOI18N
        jButton7.setText("       POS     ");
        jButton7.setAlignmentX(0.5F);
        jButton7.setAlignmentY(0.0F);
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        ManageDistributorsL.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 260, 60));

        ManageDistributorsR.setBackground(new java.awt.Color(204, 255, 255));
        ManageDistributorsR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        ManageDistributorsR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ManageDistributorsR.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 30, 30));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setForeground(new java.awt.Color(204, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorder(null);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ManageDistributorsR.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 30, 30));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\images\\history.png"));
        jButton10.setText("  HISTORY");
        jButton10.setAlignmentY(0.0F);
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton10.setIconTextGap(5);
        jButton10.setPreferredSize(new java.awt.Dimension(202, 107));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        ManageDistributorsR.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 660, 260, 60));

        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ManageDistributorsR.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1030, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("ADD DISTRIBUTOR");
        ManageDistributorsR.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 450, 50));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ManageDistributorsR.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1090, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Name Of Company");
        ManageDistributorsR.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, 20));

        companynametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        companynametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        companynametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companynametxtActionPerformed(evt);
            }
        });
        companynametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                companynametxtKeyReleased(evt);
            }
        });
        ManageDistributorsR.add(companynametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 280, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Name Of Supplier");
        ManageDistributorsR.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, -1));

        suppliertxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        suppliertxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        suppliertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliertxtActionPerformed(evt);
            }
        });
        suppliertxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                suppliertxtKeyReleased(evt);
            }
        });
        ManageDistributorsR.add(suppliertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 280, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Contact Number");
        ManageDistributorsR.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 150, -1));

        contacttxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        contacttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacttxtActionPerformed(evt);
            }
        });
        contacttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contacttxtKeyReleased(evt);
            }
        });
        ManageDistributorsR.add(contacttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 280, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Balance");
        ManageDistributorsR.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 130, -1));

        balancetxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        balancetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        balancetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancetxtActionPerformed(evt);
            }
        });
        balancetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                balancetxtKeyReleased(evt);
            }
        });
        ManageDistributorsR.add(balancetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 280, 30));

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        ManageDistributorsR.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 40, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton4.setText(" Add");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setIconTextGap(10);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        ManageDistributorsR.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 110, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton5.setText("Update");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.setIconTextGap(10);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ManageDistributorsR.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 120, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Company", "Supplier", "Contact", "Balance", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName(""); // NOI18N
        jTable1.setRowHeight(40);
        jTable1.setSelectionBackground(new java.awt.Color(0, 195, 210));
        jTable1.setShowGrid(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ManageDistributorsR.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 530, 410));
        ManageDistributorsR.add(Iconlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 40, 30));

        jButton16.setBackground(new java.awt.Color(255, 255, 153));
        jButton16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit Products.png"))); // NOI18N
        jButton16.setText("Assign Products ");
        jButton16.setToolTipText("");
        jButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        ManageDistributorsR.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 620, 250, 110));

        jButton14.setBackground(new java.awt.Color(185, 255, 153));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add Distributor.png"))); // NOI18N
        jButton14.setText(" Add Distributor");
        jButton14.setToolTipText("");
        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jButton14.setIconTextGap(1);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        ManageDistributorsR.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 290, 130));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        ManageDistributorsR.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1090, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManageDistributorsL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManageDistributorsR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ManageDistributorsL, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ManageDistributorsR, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new ManageUsers());
        f.revalidate();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new AdminDashboard());
        f.revalidate();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new LoginPanel());
        f.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new Reports());
        f.revalidate();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new History());
        f.revalidate();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new EditProducts());
        f.revalidate();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new PosPanel());
        f.revalidate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Do you really want to close this application?", "Pharmacy Management System",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        f.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void companynametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companynametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companynametxtActionPerformed

    private void companynametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_companynametxtKeyReleased
        // TODO add your handling code here:
        String company_name = companynametxt.getText();

        if (!company_name.equals("")) {
            CheckName = 0;

            Connection con;
            Statement stm;
            ResultSet rs;

            try {
                // 1. Get a connection to database
                con = ConnectionProvider.getcon();

                // 2. Create a statement
                stm = con.createStatement();

                // 3. Execute SQL query
                rs = stm.executeQuery("select * from distributors");

                for (int i = 0; i < jTable1.getRowCount(); i++) {

                    rs.next();

                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                    if (rs.getString("company_name").equals(company_name)) {
                        CheckName = 1;

                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_companynametxtKeyReleased

    private void suppliertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliertxtActionPerformed

    private void suppliertxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_suppliertxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliertxtKeyReleased

    private void contacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacttxtActionPerformed

    private void contacttxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contacttxtKeyReleased
        // TODO add your handling code here:
        String mobile_number = contacttxt.getText();

        if (!mobile_number.equals("")) {
            Iconlabel2.setVisible(true);
            Iconlabel2.setIcon(new ImageIcon("src\\images\\no.png"));
            Iconlabel2.setText("");

            if (mobile_number.length() != 11) {
                Iconlabel2.setIcon(new ImageIcon("src\\images\\no.png"));
                Iconlabel2.setText("");
            } else {
                Iconlabel2.setIcon(new ImageIcon("src\\images\\yes.png"));
            }
        } else {
            Iconlabel2.setVisible(false);
        }
    }//GEN-LAST:event_contacttxtKeyReleased

    private void balancetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balancetxtActionPerformed

    private void balancetxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_balancetxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_balancetxtKeyReleased

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        companynametxt.setText("");
        suppliertxt.setText("");
        contacttxt.setText("");
        balancetxt.setText("");
        Iconlabel2.setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String company = companynametxt.getText().toUpperCase();
        String supplier = suppliertxt.getText();
        String contact = contacttxt.getText();
        String balance = balancetxt.getText();

        Connection con, c;
        PreparedStatement stm;
        Statement st;
        int a = 0;

        try {
            c = ConnectionProvider.getcon();
            st = c.createStatement();
            ResultSet rs = st.executeQuery("Select * From distributors");

            while (rs.next()) {
                if (rs.getString("company_name").equals(company)) {
                    a = 1;
                }
            }

            c.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        if (company.equals("")) {
            JOptionPane.showMessageDialog(null, "Company name cannot be empty!");
        } else if (!contact.matches(MobileNumberPattern) || contact.length() != 11 && !contact.equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid contact number!");
        } else if (!balance.matches(decimalpattern) && !balance.matches(integerPattern) && !(balance.matches(""))) {
            JOptionPane.showMessageDialog(null, "Invalid balance pattern!\nBalance field should contain integers or decimal vales.");
        } else if (CheckName == 1) {
            JOptionPane.showMessageDialog(null, "Company name already exists!\nPlease enter another Company name.");
        } else if (a == 1) {
            JOptionPane.showMessageDialog(null, "Company name already exists!\nPlease enter another Company name.");
        } else {

            try {
                con = ConnectionProvider.getcon();

                stm = con.prepareStatement("insert into distributors (company_name,supplier,contact,balance) values(?,?,?,?)");

                stm.setString(1, company);
                stm.setString(2, supplier);
                stm.setString(3, contact);

                if (balance.equals("")) {
                    stm.setInt(4, 0);

                } else {
                    stm.setString(4, balance);

                }

                stm.executeUpdate();

                JOptionPane.showMessageDialog(null, "Distributor added successfully!");

                jTable1ComponentShown();
                jButton17ActionPerformed(evt);

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String Oname = (String) model.getValueAt(index, 1);
        String Nname = companynametxt.getText();

        if (index == -1) {
            JOptionPane.showMessageDialog(null, "Please select a record to edit!");
        } else {
            String Ocompany_name = (String) model.getValueAt(index, 1);

            String Ncompany_name = companynametxt.getText().toUpperCase();
            String supplier = suppliertxt.getText();
            String contact = contacttxt.getText();
            String balance = balancetxt.getText();

            if (Ncompany_name.equals("")) {
                JOptionPane.showMessageDialog(null, "Company name cannot be empty!");
            } else if (!contact.matches(MobileNumberPattern) || contact.length() != 11 && !contact.equals("")) {
                JOptionPane.showMessageDialog(null, "Invalid contact number!");
            } else if (!balance.matches(decimalpattern) && !balance.matches(integerPattern) && !(balance.matches(""))) {
                JOptionPane.showMessageDialog(null, "Invalid balance pattern!\nBalance field should contain integers or decimal vales.");
            } else if (CheckName == 1 && !Oname.equals(Nname)) {
                JOptionPane.showMessageDialog(null, "Company name already exists!\nPlease enter another name");
            } else {

                Connection con;
                PreparedStatement stm;

                try {
                    con = ConnectionProvider.getcon();
                    stm = con.prepareStatement("UPDATE `pharmacy`.`distributors` SET `company_name` = ? , `supplier` = ? , `contact` = ? ,"
                            + " `balance` = ? WHERE (`company_name` = ?);");

                    stm.setString(1, Ncompany_name);
                    stm.setString(2, supplier);
                    stm.setString(3, contact);

                    if (balance.equals("")) {
                        stm.setInt(4, 0);

                    } else {
                        stm.setString(4, balance);

                    }
                    stm.setString(5, Ocompany_name);

                    stm.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Changes Saved successfully!");

                    //refreshing the table
                    jTable1ComponentShown();
                    jButton17ActionPerformed(evt);

                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        String company_name = (String) model.getValueAt(index, 1);
        String supplier = (String) model.getValueAt(index, 2);
        String contact = (String) model.getValueAt(index, 3);
        String balance = (String) model.getValueAt(index, 4);

        companynametxt.setText(company_name);
        suppliertxt.setText(supplier);
        contacttxt.setText(contact);
        balancetxt.setText(balance);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        try {
            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            Connection con = ConnectionProvider.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * From distributors");

            int i = 1;
            while (rs.next()) {
                model.addRow(new Object[]{i, rs.getString("company_name"), rs.getString("supplier"), rs.getString("contact"),
                    rs.getString("balance")});
                i++;
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTable1ComponentShown

    private void jTable1ComponentShown() {
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        try {
            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            Connection con = ConnectionProvider.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * From distributors");

            int i = 1;
            while (rs.next()) {
                model.addRow(new Object[]{i, rs.getString("company_name"), rs.getString("supplier"), rs.getString("contact"),
                    rs.getString("balance")});
                i++;
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        f.getContentPane().removeAll();
        f.getContentPane().add(new AssignProducts());
        f.revalidate();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Iconlabel2;
    private javax.swing.JPanel ManageDistributorsL;
    private javax.swing.JPanel ManageDistributorsR;
    private javax.swing.JTextField balancetxt;
    private javax.swing.JTextField companynametxt;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField suppliertxt;
    // End of variables declaration//GEN-END:variables
}
